### ISSUE TITLE
Attempt to implement `Loaf` in a `LoafN` compatible way

### ISSUE THREAD

**Issue by Plecra** [Soveu/loaf#3]
Before release, it'd be great to make sure that `Loaf` could be implemented like this once const generics were stabilized:

```rust
pub type Loaf<T> = LoafN<T, 1>;
```

Afaik, this shouldn't require any changes for now, but I think it's worth keeping in mind

**Comment by Soveu** [comment]
Oh, sorry that it took me a week to reply, I just wasn't paying attention to this crate
I treated it more like a proof-of-concept rather than something that someone would consider using

Anyway, in the first version there was such a line, but while re-ordering things I decided to [comment it out](https://github.com/Soveu/loaf/blob/master/src/loaf_nightly.rs#L3) just to keep things simple

**Comment by Soveu** [comment]
Originally the definition supposed to be
```rust
pub struct Loaf<T, const N: usize = 1>
```
but this is not yet supported by rustc

**Comment by Soveu** [comment]
Well, now it is, so I'm gonna close this issue :)
